version: "3.8"

services:
    postgres:
        container_name: lifefolio_db
        image: postgres:alpine
        environment:
            POSTGRES_HOST: ${POSTGRES_HOST}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - ./docker-volumes/postgres:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        container_name: lifefolio_redis
        image: redis:alpine
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        ports:
            - "6379:6379"
        volumes:
            - ./docker-volumes/redis:/data
